import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/header/header';
import Breadcrumb from '@/components/breadcrumb/breadcrumb';
import Footer from './footer';
import themeArea from '@/pages/theme-area.module.scss';
import '../../styles/global.css';

const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className={themeArea.main}>
          <Header />
          <div className={`px-2 lg:px-0 ${themeArea.content}`}>
            <Breadcrumb />
            <div className="container mx-auto py-4">
              {children}
            </div>
          </div>
          <Footer />
      </main>
      </body>
    </html>
  )
}
